version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/web.dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
      - ./config:/etc/httpd/conf
      - ./logs:/usr/local/apache2/logs
    ports:
      - "8080:80"
    networks:
      - app-network

  db:
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
