version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./dockerfiles/php.dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    ports:
     - "9000:9000"

  apache:
    image: httpd:2.4
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./config:/usr/local/apache2/conf
      - ./src:/var/www/html
      - ./logs:/usr/local/apache2/logs
    networks:
      - app-network

  db:
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
